name: CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build-essential
      run: sudo apt-get update && sudo apt-get install build-essential -y
    - name: local.properties pretixscan
      run: echo "github.token=${{ secrets.GITHUB_TOKEN }}" > local.properties
      working-directory: ./pretixscan
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Submodules
      run: git submodule update --init
      working-directory: ./pretixscan
    - name: Run Linters
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: TERM=dumb ./gradlew lintPretixDebug
      working-directory: ./pretixscan

    - name: Decode release keystore
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > release.keystore

    - name: Build Release APK
      if: startsWith(github.ref, 'refs/tags/')
      env:
        KSTOREPWD: ${{ secrets.KSTOREPWD }}
      run: TERM=dumb ./gradlew assemblePretixRelease
      working-directory: ./pretixscan
      
    - name: Upload APK
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: pretixscan-apk
        path: pretixscan/app/build/outputs/apk/pretix/release/*.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: pretixscan/app/build/outputs/apk/pretix/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: pretixscan/app/build/outputs/apk/pretix/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
