name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build-essential
      run: sudo apt-get update && sudo apt-get install build-essential -y
    - name: local.properties pretixscan
      run: echo "github.token=${{ secrets.GITHUB_TOKEN }}" > local.properties
      working-directory: ./pretixscan
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Submodules
      run: git submodule update --init
      working-directory: ./pretixscan
    - name: Decode release keystore
      run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > release.keystore
    - name: Unit tests
      env:
        KSTOREPWD: ${{ secrets.KSTOREPWD }}
      run: TERM=dumb ./gradlew lintPretixDebug assemblePretixRelease
      working-directory: ./pretixscan
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pretixscan-apk
        path: pretixscan/app/build/outputs/apk/pretix/release/*.apk
```
